# Generated by Django 3.1.3 on 2020-12-14 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mame', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100, verbose_name='Dia')),
                ('horaIngreso', models.CharField(max_length=100, verbose_name='Hora de ingreso')),
                ('horaSalida', models.CharField(max_length=100, verbose_name='Hora de salida')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='nombre')),
                ('lastName', models.CharField(max_length=100, verbose_name='apellidos')),
                ('age', models.IntegerField(verbose_name='edad')),
                ('DNI', models.IntegerField(unique=True, verbose_name='DNI')),
                ('seguro', models.IntegerField(unique=True, verbose_name='seguro')),
                ('telefono', models.IntegerField(unique=True, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameD', models.CharField(max_length=100, verbose_name='nombre')),
                ('LastNameD', models.CharField(max_length=100, verbose_name='Apellido')),
                ('especialidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.especialidad', verbose_name='especidalidad de doctor')),
                ('horario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.horario', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.CharField(max_length=100, verbose_name='Hora')),
                ('medico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.medico', verbose_name='Medico')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
