# Generated by Django 3.1.3 on 2020-12-14 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.RenameField(
            model_name='especialidad',
            old_name='mame',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.especialidad', verbose_name='especidalidad del medico'),
        ),
    ]
