# Generated by Django 3.1.3 on 2020-12-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_auto_20201214_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='Fecha',
            field=models.DateTimeField(blank=True),
        ),
    ]
